<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-02-25T18:07:44 IST" name="Default suite" finished-at="2025-02-25T18:08:26 IST" duration-ms="41913">
    <groups>
    </groups>
    <test started-at="2025-02-25T18:07:44 IST" name="Default test" finished-at="2025-02-25T18:08:26 IST" duration-ms="41913">
      <class name="businessUser.Deal">
        <test-method is-config="true" signature="setUp()[pri:0, instance:businessUser.Deal@201a4587]" started-at="2025-02-25T18:07:44 IST" name="setUp" finished-at="2025-02-25T18:07:46 IST" duration-ms="1916" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="createdealBybusinessUserAndAdminApprovesTheDeal()[pri:1, instance:businessUser.Deal@201a4587]" started-at="2025-02-25T18:07:46 IST" name="createdealBybusinessUserAndAdminApprovesTheDeal" finished-at="2025-02-25T18:08:15 IST" duration-ms="29269" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createdealBybusinessUserAndAdminApprovesTheDeal -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:businessUser.Deal@201a4587]" started-at="2025-02-25T18:08:15 IST" name="setUp" finished-at="2025-02-25T18:08:16 IST" duration-ms="1218" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="dealCreatedNowCheckTheMainDashboardDealsCountAndAfterThatGoToDealDashboardAndCheckTheRemainingDealCountAndActiveDealcount()[pri:2, instance:businessUser.Deal@201a4587]" started-at="2025-02-25T18:08:16 IST" name="dealCreatedNowCheckTheMainDashboardDealsCountAndAfterThatGoToDealDashboardAndCheckTheRemainingDealCountAndActiveDealcount" finished-at="2025-02-25T18:08:26 IST" depends-on-methods="businessUser.Deal.createdealBybusinessUserAndAdminApprovesTheDeal" duration-ms="9490" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Active count did not increase by 1! expected [2] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Active count did not increase by 1! expected [2] but found [1]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at businessUser.Deal.dealCreatedNowCheckTheMainDashboardDealsCountAndAfterThatGoToDealDashboardAndCheckTheRemainingDealCountAndActiveDealcount(Deal.java:154)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dealCreatedNowCheckTheMainDashboardDealsCountAndAfterThatGoToDealDashboardAndCheckTheRemainingDealCountAndActiveDealcount -->
      </class> <!-- businessUser.Deal -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
